/*****************************************************************************/
/*   Cflags.c: generated by mkcflags on Sat Jul 12, 2014 08:41:48 AM         */
/*****************************************************************************/
#include "config.h"
#include <time.h>
#include INC_SYS_TIME

char cflags[]="gcc  -g -Wall  -DRSA   -g ";
char arch[]="linux";
char cdate[]="07/12/14";
struct timeval tv_ctime={1405147308,0};
char cbugs[]="feedback to: quozl@us.netrek.org";
char cowid[]="COW 3.3.0, linux, 07/12/14, RMCSAmTsrP";
char cwho[]="henry@einstein.home";
